# DSPy tutorial

In [2]:
%load_ext autoreload
%autoreload 2
%load_ext dotenv
%dotenv

In [31]:
import dspy
from dspy.evaluate import Evaluate
import pandas as pd

## Import data

In [7]:
df = pd.read_csv('data/brass_birmingham-selected.csv')
df.head(3)

,url,question,answer,manual quote 1,manual quote 2,manual quote 3,manual quote 4,manual quote 5,manual quote 6,manual quote 7,manual quote 8
0,https://boardgamegeek.com/thread/2096967/doubl...,May I connect another players brewery with two...,"When laying two rail links, each one is consid...","In a single Network action, you may build a ma...",You must consume 1 coal for each\nrail Link bu...,NaN,NaN,NaN,NaN,NaN,NaN
1,https://boardgamegeek.com/thread/2901920/which...,"Since you need coal to build a rail link, and ...","To consume coal, you need to be connected to a...","To consume coal, a rail Link or Industry tile ...",Coal must be consumed from: 1 The closest (few...,2 If you are not connected to an unflipped Coa...,NaN,NaN,NaN,NaN,NaN
2,https://boardgamegeek.com/thread/3087643/cards...,"In a 4 player game, there are 64 action cards....","Yes, the first round of the game has only one ...",Player Area Setup:,8- Draw 8 cards from the Draw Deck; this is yo...,There are exactly 8/9/10 rounds per era in a 4...,"On your turn, perform a total of 2 actions.\nE...",NaN,NaN,NaN,NaN

In [9]:
# keep only rows with quotes
df = df[df['manual quote 1'] > '']
len(df)

180

In [12]:
# join all of the manual quote columns together 
quote_columns = [f'manual quote {i}' for i in range(1, 9)]
df['manual quote'] = df[quote_columns].apply(
    lambda row: '\n\n'.join(row.dropna().astype(str)),
    axis=1
)
df.head(3)

,url,question,answer,manual quote 1,manual quote 2,manual quote 3,manual quote 4,manual quote 5,manual quote 6,manual quote 7,manual quote 8,manual quote
0,https://boardgamegeek.com/thread/2096967/doubl...,May I connect another players brewery with two...,"When laying two rail links, each one is consid...","In a single Network action, you may build a ma...",You must consume 1 coal for each\nrail Link bu...,NaN,NaN,NaN,NaN,NaN,NaN,"In a single Network action, you may build a ma..."
1,https://boardgamegeek.com/thread/2901920/which...,"Since you need coal to build a rail link, and ...","To consume coal, you need to be connected to a...","To consume coal, a rail Link or Industry tile ...",Coal must be consumed from: 1 The closest (few...,2 If you are not connected to an unflipped Coa...,NaN,NaN,NaN,NaN,NaN,"To consume coal, a rail Link or Industry tile ..."
2,https://boardgamegeek.com/thread/3087643/cards...,"In a 4 player game, there are 64 action cards....","Yes, the first round of the game has only one ...",Player Area Setup:,8- Draw 8 cards from the Draw Deck; this is yo...,There are exactly 8/9/10 rounds per era in a 4...,"On your turn, perform a total of 2 actions.\nE...",NaN,NaN,NaN,NaN,Player Area Setup:\n\n8- Draw 8 cards from the...

In [13]:
# drop the other columns
df = df.drop(columns=quote_columns)

In [17]:
# turn dataset into dspy examples
examples = []

for index, row in df.iterrows():
    example = dspy.Example(
        question=row['question'],
        context=row['manual quote'],
        answer= row['answer'],
    ).with_inputs('question', 'context')
    examples.append(example)
len(examples)

180

In [55]:
# split into train and test
train = examples[:100]
dev = examples[100:140]
test = examples[140:]
print(len(train), len(dev), len(test))

100 40 40

## Set up DSPy

define signatures and modules

In [22]:
lm = dspy.OpenAI(model="gpt-4o-mini")
dspy.settings.configure(lm=lm)

In [20]:
class GenerateAnswer(dspy.Signature):
    """Answer questions from contexts."""

    context = dspy.InputField(desc="may contain relevant facts")
    question = dspy.InputField()
    answer = dspy.OutputField()

In [27]:
class AnswerGenerator(dspy.Module):
    def __init__(self):
        super().__init__()

        self.generate_answer = dspy.ChainOfThought(GenerateAnswer)
    
    def forward(self, question, context):
        prediction = self.generate_answer(context=context, question=question)
        return dspy.Prediction(context=context, answer=prediction.answer)

In [56]:
# make sure everything works
answer_generator = AnswerGenerator()
prediction = answer_generator(test[0]['question'], test[0]['context'])
print(test[0])
print(prediction)

Example({'question': 'If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?', 'context': 'Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.', 'answer': "You lose them. Overbuilt tiles (whether yours or an opponent's) do not score any VP, because they cease to exist."}) (input_keys={'question', 'context'})
Prediction(
    context='Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.',
    answer='You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.'
)

In [57]:
lm.inspect_history(n=1)

Answer questions from contexts.

---

Follow the following format.

Context: may contain relevant facts

Question: ${question}

Reasoning: Let's think step by step in order to ${produce the answer}. We ...

Answer: ${answer}

---

Context: Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.

Question: If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?

Reasoning: Let's think step by step in order to determine the impact of overbuilding a flipped tile on scoring. The context states that overbuilt Industry tiles are removed from the game and returned to the box, meaning they will not score Victory Points (VPs). It also mentions that players do not lose previously gained income or VPs if their Industry tiles are overbuilt. Therefore, if I overbuild a flipped tile, I will not score any points for it at the end of the current era, as the tile is removed and does not contribute to scoring.

Answer: You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.

"\n\n\nAnswer questions from contexts.\n\n---\n\nFollow the following format.\n\nContext: may contain relevant facts\n\nQuestion: ${question}\n\nReasoning: Let's think step by step in order to ${produce the answer}. We ...\n\nAnswer: ${answer}\n\n---\n\nContext: Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.\n\nQuestion: If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?\n\nReasoning: Let's think step by step in order to\x1b[32m determine the impact of overbuilding a flipped tile on scoring. The context states that overbuilt Industry tiles are removed from the game and returned to the box, meaning they will not score Victory Points (VPs). It also mentions that players do not lose previously gained income or VPs if their Industry tiles are overbuilt. Therefore, if I overbuild a flipped tile, I will not score any points for it at the end of the current era, as the tile is removed and does not contribute to scoring.\n\nAnswer: You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.\x1b[0m\n\n\n"

## Define evaluation metrics

In [64]:
# set up metrics
metric_lm = dspy.OpenAI(model='gpt-4o', max_tokens=1000, model_type='chat')

class Assess(dspy.Signature):
    """Assess the quality of an answer along the specified dimension."""
    
    context = dspy.InputField(desc="ignore if N/A")
    assessed_text = dspy.InputField()
    assessment_question = dspy.InputField()
    assessment_answer = dspy.OutputField(desc="Yes or No")

def llm_metric(gold, pred, trace=None):
    question, answer, context = gold.question, gold.answer, gold.context
    predicted_answer = pred.answer

    faithfulness_question = "Is the assessed text grounded in the context? " + \
                            "Say no if it includes significant facts not in the context."
    correctness_question = f"The text above should answer `{question}`. The gold answer is `{answer}'. " + \
                           "Does the assessed text above contain the gold answer?"

    with dspy.context(lm=metric_lm):
        faithfulness_answer = dspy.Predict(Assess)(
            context=context, 
            assessed_text=predicted_answer, 
            assessment_question=faithfulness_question,
        )
        correctness_answer = dspy.Predict(Assess)(
            context='N/A', 
            assessed_text=predicted_answer, 
            assessment_question=correctness_question,
        )
    
    faithfulness_score, correctness_score = (any(w.lower() == 'yes' for w in m.assessment_answer.split()) \
                                             for m in [faithfulness_answer, correctness_answer])

    # print(f"Faithful: {faithfulness_answer.assessment_answer}, score={faithfulness_score}")
    # print(f"Correct: {correctness_answer.assessment_answer}, score={correctness_score}")
    
    score = float(faithfulness_score) + float(correctness_score)

    if trace is not None: 
        return score >= 2
        
    return score / 2.0

In [59]:
gold = test[0]
print(f"question {gold.question}")
print(f"gold answer {gold.answer}")
print(f"pred answer {prediction.answer}")
llm_metric(gold, prediction)

question If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?
gold answer You lose them. Overbuilt tiles (whether yours or an opponent's) do not score any VP, because they cease to exist.
pred answer You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.
Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False

0.5

In [60]:
metric_lm.inspect_history(n=2)

Assess the quality of an answer along the specified dimension.

---

Follow the following format.

Context: ignore if N/A

Assessed Text: ${assessed_text}

Assessment Question: ${assessment_question}

Assessment Answer: Yes or No

---

Context: Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.

Assessed Text: You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.

Assessment Question: Is the assessed text grounded in the context? Say no if it includes significant facts not in the context.

Assessment Answer: Assessment Answer: Yes





Assess the quality of an answer along the specified dimension.

---

Follow the following format.

Context: ignore if N/A

Assessed Text: ${assessed_text}

Assessment Question: ${assessment_question}

Assessment Answer: Yes or No

---

Context: N/A

Assessed Text: You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.

Assessment Question: The text above should answer `If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?`. The gold answer is `You lose them. Overbuilt tiles (whether yours or an opponent's) do not score any VP, because they cease to exist.'. Does the assessed text above contain the gold answer?

Assessment Answer: No

"\n\n\nAssess the quality of an answer along the specified dimension.\n\n---\n\nFollow the following format.\n\nContext: ignore if N/A\n\nAssessed Text: ${assessed_text}\n\nAssessment Question: ${assessment_question}\n\nAssessment Answer: Yes or No\n\n---\n\nContext: Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.\n\nAssessed Text: You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.\n\nAssessment Question: Is the assessed text grounded in the context? Say no if it includes significant facts not in the context.\n\nAssessment Answer:\x1b[32m Assessment Answer: Yes\x1b[0m\n\n\n\n\n\nAssess the quality of an answer along the specified dimension.\n\n---\n\nFollow the following format.\n\nContext: ignore if N/A\n\nAssessed Text: ${assessed_text}\n\nAssessment Question: ${assessment_question}\n\nAssessment Answer: Yes or No\n\n---\n\nContext: N/A\n\nAssessed Text: You do not score any points for the overbuilt tile at the end of the current era; it is removed and does not contribute to scoring.\n\nAssessment Question: The text above should answer `If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?`. The gold answer is `You lose them. Overbuilt tiles (whether yours or an opponent's) do not score any VP, because they cease to exist.'. Does the assessed text above contain the gold answer?\n\nAssessment Answer:\x1b[32m No\x1b[0m\n\n\n"

## Evaluate uncompiled prompt

In [61]:
# set up evaluator
evaluator = Evaluate(devset=test, num_threads=1, display_progress=True, display_table=5)

In [52]:
# launch evaluation
evaluator(answer_generator, metric=llm_metric)

  0%|                                                              | 0/40 [00:00<?, ?it/s]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 0.5 / 1  (50.0):   2%|▌                    | 1/40 [00:01<01:13,  1.89s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 0.5 / 2  (25.0):   5%|█                    | 2/40 [00:03<01:03,  1.68s/it]Faithful: Assessment Answer: No, score=False
Correct: No, score=False
Average Metric: 0.5 / 3  (16.7):   8%|█▌                   | 3/40 [00:05<01:11,  1.93s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 0.5 / 4  (12.5):  10%|██                   | 4/40 [00:08<01:19,  2.20s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 0.5 / 5  (10.0):  12%|██▋                  | 5/40 [00:10<01:14,  2.12s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 0.5 / 6  (8.3):  15%|███▎                  | 6/40 [00:12<01:15,  2.23s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 0.5 / 7  (7.1):  18%|███▊                  | 7/40 [00:14<01:06,  2.00s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 1.0 / 8  (12.5):  20%|████▏                | 8/40 [00:17<01:12,  2.28s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 1.0 / 9  (11.1):  22%|████▋                | 9/40 [00:19<01:10,  2.26s/it]Faithful: Assessment Answer: No, score=False
Correct: No, score=False
Average Metric: 1.0 / 10  (10.0):  25%|████▊              | 10/40 [00:21<01:09,  2.30s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 1.0 / 11  (9.1):  28%|█████▌              | 11/40 [00:23<01:01,  2.12s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 1.0 / 12  (8.3):  30%|██████              | 12/40 [00:24<00:53,  1.90s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 1.0 / 13  (7.7):  32%|██████▌             | 13/40 [00:28<01:02,  2.33s/it]Faithful: Assessment Answer: Yes, score=True
Correct: Assessment Answer: Yes, score=True
Average Metric: 2.0 / 14  (14.3):  35%|██████▋            | 14/40 [00:30<01:00,  2.31s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 2.5 / 15  (16.7):  38%|███████▏           | 15/40 [00:33<01:01,  2.47s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 2.5 / 16  (15.6):  40%|███████▌           | 16/40 [00:36<01:01,  2.58s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 2.5 / 17  (14.7):  42%|████████           | 17/40 [00:38<00:56,  2.45s/it]Faithful: Assessment Answer: Yes, score=True
Correct: Yes, score=True
Average Metric: 3.5 / 18  (19.4):  45%|████████▌          | 18/40 [00:40<00:55,  2.54s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 4.0 / 19  (21.1):  48%|█████████          | 19/40 [00:42<00:48,  2.30s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 4.0 / 20  (20.0):  50%|█████████▌         | 20/40 [00:44<00:43,  2.18s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 4.5 / 21  (21.4):  52%|█████████▉         | 21/40 [00:48<00:49,  2.63s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 4.5 / 22  (20.5):  55%|██████████▍        | 22/40 [00:50<00:42,  2.39s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 5.0 / 23  (21.7):  57%|██████████▉        | 23/40 [00:52<00:41,  2.41s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.0 / 24  (20.8):  60%|███████████▍       | 24/40 [00:55<00:43,  2.71s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.0 / 25  (20.0):  62%|███████████▉       | 25/40 [00:57<00:36,  2.42s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.0 / 26  (19.2):  65%|████████████▎      | 26/40 [01:05<00:55,  3.99s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.0 / 27  (18.5):  68%|████████████▊      | 27/40 [01:07<00:44,  3.44s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 5.5 / 28  (19.6):  70%|█████████████▎     | 28/40 [01:09<00:35,  2.94s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.5 / 29  (19.0):  72%|█████████████▊     | 29/40 [01:11<00:28,  2.63s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.5 / 30  (18.3):  75%|██████████████▎    | 30/40 [01:13<00:26,  2.64s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 5.5 / 31  (17.7):  78%|██████████████▋    | 31/40 [01:16<00:23,  2.60s/it]Faithful: Assessment Answer: No, score=False
Correct: Assessment Answer: Yes, score=True
Average Metric: 6.0 / 32  (18.8):  80%|███████████████▏   | 32/40 [01:18<00:19,  2.40s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 6.0 / 33  (18.2):  82%|███████████████▋   | 33/40 [01:20<00:16,  2.38s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 6.0 / 34  (17.6):  85%|████████████████▏  | 34/40 [01:22<00:13,  2.29s/it]Faithful: Assessment Answer: No, score=False
Correct: Yes, score=True
Average Metric: 6.5 / 35  (18.6):  88%|████████████████▋  | 35/40 [01:24<00:10,  2.00s/it]Faithful: Yes, score=True
Correct: Yes, score=True
Average Metric: 7.5 / 36  (20.8):  90%|█████████████████  | 36/40 [01:25<00:07,  1.82s/it]Faithful: Assessment Answer: Yes, score=True
Correct: No, score=False
Average Metric: 8.0 / 37  (21.6):  92%|█████████████████▌ | 37/40 [01:27<00:06,  2.03s/it]Faithful: Yes, score=True
Correct: No, score=False
Average Metric: 8.5 / 38  (22.4):  95%|██████████████████ | 38/40 [01:31<00:05,  2.52s/it]Faithful: No, score=False
Correct: No, score=False
Average Metric: 8.5 / 39  (21.8):  98%|██████████████████▌| 39/40 [01:33<00:02,  2.28s/it]Faithful: Yes, score=True
Correct: No, score=False
Average Metric: 9.0 / 40  (22.5): 100%|███████████████████| 40/40 [01:35<00:00,  2.38s/it]

22.5

## Compile prompt

In [73]:
from dspy.teleprompt import BootstrapFewShotWithRandomSearch

# Set up the optimizer: we want to "bootstrap" (i.e., self-generate) 8-shot examples of your program's steps.
# The optimizer will repeat this 10 times (plus some initial attempts) before selecting its best attempt on the devset.

teleprompter = BootstrapFewShotWithRandomSearch(
    metric=llm_metric,
    max_labeled_demos=4,
    max_bootstrapped_demos=1,
    num_candidate_programs=10,
    num_threads=4,
)

Going to sample between 1 and 1 traces per predictor.
Will attempt to bootstrap 10 candidate sets.

In [74]:
answer_generator_compiled = teleprompter.compile(answer_generator, trainset=train, valset=dev)

Average Metric: 13.0 / 40  (32.5): 100%|████████████████| 40/40 [00:00<00:00, 1752.54it/s]

Score: 32.5 for set: [0]
New best sscore: 32.5 for seed -3
Scores so far: [32.5]
Best score: 32.5

Average Metric: 14.0 / 40  (35.0): 100%|████████████████| 40/40 [00:00<00:00, 1503.11it/s]

Score: 35.0 for set: [4]
New best sscore: 35.0 for seed -2
Scores so far: [32.5, 35.0]
Best score: 35.0

  9%|████▋                                               | 9/100 [00:00<00:00, 713.37it/s]

Bootstrapped 1 full traces after 10 examples in round 0.

Average Metric: 12.5 / 40  (31.2): 100%|██████████████████| 40/40 [00:20<00:00,  1.97it/s]

Score: 31.25 for set: [4]
Scores so far: [32.5, 35.0, 31.25]
Best score: 35.0
Average of max per entry across top 1 scores: 0.35
Average of max per entry across top 2 scores: 0.3875
Average of max per entry across top 3 scores: 0.45
Average of max per entry across top 5 scores: 0.45
Average of max per entry across top 8 scores: 0.45
Average of max per entry across top 9999 scores: 0.45

  2%|█                                                   | 2/100 [00:00<00:00, 664.44it/s]

Bootstrapped 1 full traces after 3 examples in round 0.

Average Metric: 16.0 / 40  (40.0): 100%|██████████████████| 40/40 [00:22<00:00,  1.81it/s]

Score: 40.0 for set: [4]
New best sscore: 40.0 for seed 0
Scores so far: [32.5, 35.0, 31.25, 40.0]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.525
Average of max per entry across top 9999 scores: 0.525

 12%|██████                                             | 12/100 [00:00<00:00, 797.91it/s]

Bootstrapped 1 full traces after 13 examples in round 0.

Average Metric: 14.0 / 40  (35.0): 100%|██████████████████| 40/40 [00:15<00:00,  2.53it/s]

Score: 35.0 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.525
Average of max per entry across top 9999 scores: 0.525

 18%|█████████▏                                         | 18/100 [00:00<00:00, 834.09it/s]

Bootstrapped 1 full traces after 19 examples in round 0.

Average Metric: 13.5 / 40  (33.8): 100%|████████████████| 40/40 [00:00<00:00, 1570.78it/s]

Score: 33.75 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.5375
Average of max per entry across top 9999 scores: 0.5375

 16%|████████▏                                          | 16/100 [00:00<00:00, 789.03it/s]

Bootstrapped 1 full traces after 17 examples in round 0.

Average Metric: 12.0 / 40  (30.0): 100%|██████████████████| 40/40 [00:21<00:00,  1.82it/s]

Score: 30.0 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.5375
Average of max per entry across top 9999 scores: 0.5375

 17%|████████▋                                          | 17/100 [00:00<00:00, 825.38it/s]

Bootstrapped 1 full traces after 18 examples in round 0.

Average Metric: 13.0 / 40  (32.5): 100%|██████████████████| 40/40 [00:17<00:00,  2.33it/s]

Score: 32.5 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0, 32.5]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.55
Average of max per entry across top 9999 scores: 0.55

  5%|██▌                                                 | 5/100 [00:00<00:00, 755.35it/s]

Bootstrapped 1 full traces after 6 examples in round 0.

Average Metric: 12.0 / 40  (30.0): 100%|██████████████████| 40/40 [00:20<00:00,  2.00it/s]

Score: 30.0 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0, 32.5, 30.0]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.55
Average of max per entry across top 9999 scores: 0.575

  9%|████▋                                               | 9/100 [00:00<00:00, 720.66it/s]

Bootstrapped 1 full traces after 10 examples in round 0.

Average Metric: 12.5 / 40  (31.2): 100%|██████████████████| 40/40 [00:17<00:00,  2.25it/s]

Score: 31.25 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0, 32.5, 30.0, 31.25]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.5875
Average of max per entry across top 9999 scores: 0.6

  7%|███▋                                                | 7/100 [00:00<00:00, 859.24it/s]

Bootstrapped 1 full traces after 8 examples in round 0.

Average Metric: 12.0 / 40  (30.0): 100%|██████████████████| 40/40 [00:19<00:00,  2.00it/s]

Score: 30.0 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0, 32.5, 30.0, 31.25, 30.0]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.5875
Average of max per entry across top 9999 scores: 0.6

  2%|█                                                   | 2/100 [00:00<00:00, 650.94it/s]

Bootstrapped 1 full traces after 3 examples in round 0.

Average Metric: 13.0 / 40  (32.5): 100%|██████████████████| 40/40 [00:16<00:00,  2.49it/s]

Score: 32.5 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0, 32.5, 30.0, 31.25, 30.0, 32.5]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.525
Average of max per entry across top 8 scores: 0.5625
Average of max per entry across top 9999 scores: 0.6

  3%|█▌                                                  | 3/100 [00:00<00:00, 841.55it/s]

Bootstrapped 1 full traces after 4 examples in round 0.

Average Metric: 14.0 / 40  (35.0): 100%|██████████████████| 40/40 [00:15<00:00,  2.57it/s]

Score: 35.0 for set: [4]
Scores so far: [32.5, 35.0, 31.25, 40.0, 35.0, 33.75, 30.0, 32.5, 30.0, 31.25, 30.0, 32.5, 35.0]
Best score: 40.0
Average of max per entry across top 1 scores: 0.4
Average of max per entry across top 2 scores: 0.5
Average of max per entry across top 3 scores: 0.5125
Average of max per entry across top 5 scores: 0.5375
Average of max per entry across top 8 scores: 0.55
Average of max per entry across top 9999 scores: 0.6
13 candidate programs found.

### Test compiled prompt

In [75]:
prediction = answer_generator_compiled(test[0]['question'], test[0]['context'])
print(test[0])
print(prediction)

Example({'question': 'If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?', 'context': 'Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.', 'answer': "You lose them. Overbuilt tiles (whether yours or an opponent's) do not score any VP, because they cease to exist."}) (input_keys={'question', 'context'})
Prediction(
    context='Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.',
    answer='No, you do not lose out on any points that you would have otherwise scored for the overbuilt tile at the end of the current era. The points are retained and will be scored at the end of the era, as players do not lose previously gained income or VPs when their Industry tiles are overbuilt.'
)

In [76]:
lm.inspect_history(n=1)

Answer questions from contexts.

---

Context:
On your turn, perform a total of 2 actions.
Exception: During the first round of the Canal Era, each player performs only 1 action.
Question: So you have always to do 2 actions, exception the first turn of the canal phase, right?
Answer: Yeah, every turn except the very first is exactly two actions, no more and no less.

Context:
Selling requires:
- Connection to a Merchant tile.
- Beer (usually).

Two locations are considered “connected”  to each other if you can trace a route of Link tiles (owned by any player) from one  location to the other
Question: Shrewsbury has only one route into it. Which I believe means that once someone puts a boat on that Canal (or train on the track in the Rail era) only that player will be able to sell Potteries. Is that the correct conclusion?
Answer: In order to sell to a market, you need only have a connection. The links in the connection may have been built by any combinations of players but it is only the actual connection that matters for your sell. Not the owners of the links.

Context:
To perform the Network Action:

Place a Link tile on an undeveloped line on the board. The placed Link tile must be adjacent to a location that is a part of your network (see “Your Network”).

A location on the board is considered to be a part of your network if at least one of the following is true:
- The location contains one or more of your Industry tiles;
- The location is adjacent to one or more of your Link tiles

In a single Network action, you may build a maximum of 2 rail Links for £15, if you also consume 1 beer. This beer must be consumed from a Brewery (not a Merchant beer).
Remember: If consuming beer from another player’s Brewery, it must be connected to the second rail Link (after it is placed)

You must consume 1 coal for each
rail Link built (see “Consuming Coal”)
Remember: Each rail Link is placed
separately and must be connected to a
source of coal (after it is placed).

Coal must be consumed from: 1 The closest (fewest Link tiles distant) connected unflipped Coal Mine

2 If you are not connected to an unflipped Coal Mine, you can purchase coal from the Coal Market.
Question: In the second era, two tracks were etched at two different places on the board in one turn without connection to each other. The player used coal from his own mine for the first track. The other line was only connected to the general market, and beer was consumed. Is that in accordance with the rules?
Answer: Per the rulebook, you must be connected to a souce of coal to consume it for each rail Link built after it's placed. Next, there has to be a beer available for the second link (not from the merchant). Both links have to be in your network.

---

Follow the following format.

Context: may contain relevant facts

Question: ${question}

Reasoning: Let's think step by step in order to ${produce the answer}. We ...

Answer: ${answer}

---

Context: Two locations are considered “connected” to each other if you can trace a route of Link tiles (owned by any player) from one location to the other

Question: Are you connected to coal via indirect routes (routes that are not entirely your own links), if there are empty cities between?

Reasoning: Let's think step by step in order to determine if you are connected to coal via indirect routes. We need to consider the definition of "connected" as stated in the context. It specifies that two locations are connected if there is a route of Link tiles from one location to the other, regardless of ownership. Therefore, we need to check if there is a continuous route of Link tiles leading to the coal, even if there are empty cities in between.

Answer: Yes, you are connected to coal via indirect routes, as long as there is a continuous route of Link tiles leading to it, regardless of ownership or empty cities in between.

---

Context: Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.

Question: If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?

Reasoning: Let's think step by step in order to determine the impact of overbuilding a flipped tile on scoring points. The context states that overbuilt Industry tiles are removed from the game and returned to the box, and importantly, players do not lose previously gained income or VPs if their Industry tiles are overbuilt. This implies that the points associated with the overbuilt tile are not lost, but it does not specify when those points are scored. Since the context does not mention scoring points immediately at the time of overbuilding, we can conclude that the points are likely scored at the end of the current era, as is typical in many games. Therefore, overbuilding a flipped tile does not result in an immediate loss of points, but rather, the points are retained until the end of the era

Answer: No, you do not lose out on any points that you would have otherwise scored for the overbuilt tile at the end of the current era. The points are retained and will be scored at the end of the era, as players do not lose previously gained income or VPs when their Industry tiles are overbuilt.

'\n\n\nAnswer questions from contexts.\n\n---\n\nContext:\nOn your turn, perform a total of 2 actions.\nException: During the first round of the Canal Era, each player performs only 1 action. \nQuestion: So you have always to do 2 actions, exception the first turn of the canal phase, right?\nAnswer: Yeah, every turn except the very first is exactly two actions, no more and no less.\n\nContext:\nSelling requires:\n- Connection to a Merchant tile.\n- Beer (usually).\n\nTwo locations are considered “connected”  to each other if you can trace a route of Link tiles (owned by any player) from one  location to the other\nQuestion: Shrewsbury has only one route into it. Which I believe means that once someone puts a boat on that Canal (or train on the track in the Rail era) only that player will be able to sell Potteries. Is that the correct conclusion?\nAnswer: In order to sell to a market, you need only have a connection. The links in the connection may have been built by any combinations of players but it is only the actual connection that matters for your sell. Not the owners of the links.\n\nContext:\nTo perform the Network Action:\n\nPlace a Link tile on an undeveloped line on the board. The placed Link tile must be adjacent to a location that is a part of your network (see “Your Network”).\n\nA location on the board is considered to be a part of your network if at least one of the following is true:\n- The location contains one or more of your Industry tiles;\n- The location is adjacent to one or more of your Link tiles\n\nIn a single Network action, you may build a maximum of 2 rail Links for £15, if you also consume 1 beer. This beer must be consumed from a Brewery (not a Merchant beer).\nRemember: If consuming beer from another player’s Brewery, it must be connected to the second rail Link (after it is placed)\n\nYou must consume 1 coal for each\nrail Link built (see “Consuming Coal”)\nRemember: Each rail Link is placed\nseparately and must be connected to a\nsource of coal (after it is placed).\n\nCoal must be consumed from: 1 The closest (fewest Link tiles distant) connected unflipped Coal Mine\n\n2 If you are not connected to an unflipped Coal Mine, you can purchase coal from the Coal Market.\nQuestion: In the second era, two tracks were etched at two different places on the board in one turn without connection to each other. The player used coal from his own mine for the first track. The other line was only connected to the general market, and beer was consumed. Is that in accordance with the rules?\nAnswer: Per the rulebook, you must be connected to a souce of coal to consume it for each rail Link built after it\'s placed. Next, there has to be a beer available for the second link (not from the merchant). Both links have to be in your network.\n\n---\n\nFollow the following format.\n\nContext: may contain relevant facts\n\nQuestion: ${question}\n\nReasoning: Let\'s think step by step in order to ${produce the answer}. We ...\n\nAnswer: ${answer}\n\n---\n\nContext: Two locations are considered “connected” to each other if you can trace a route of Link tiles (owned by any player) from one location to the other \n\nQuestion: Are you connected to coal via indirect routes (routes that are not entirely your own links), if there are empty cities between?\n\nReasoning: Let\'s think step by step in order to determine if you are connected to coal via indirect routes. We need to consider the definition of "connected" as stated in the context. It specifies that two locations are connected if there is a route of Link tiles from one location to the other, regardless of ownership. Therefore, we need to check if there is a continuous route of Link tiles leading to the coal, even if there are empty cities in between.\n\nAnswer: Yes, you are connected to coal via indirect routes, as long as there is a continuous route of Link tiles leading to it, regardless of ownership or empty cities in between.\n\n---\n\nContext: Remove overbuilt Industry tiles from the game, and return them to the box (they will not score VPs). Players do not lose previously gained income or VPs if their Industry tiles are overbuilt.\n\nQuestion: If I overbuild a flipped tile, do I lose out on any points that I would have otherwise scored for that overbuilt tile at the end of the current era? Or do I score the points immediately at the time of overbuilding?\n\nReasoning: Let\'s think step by step in order to determine the impact of overbuilding a flipped tile on scoring points. The context states that overbuilt Industry tiles are removed from the game and returned to the box, and importantly, players do not lose previously gained income or VPs if their Industry tiles are overbuilt. This implies that the points associated with the overbuilt tile are not lost, but it does not specify when those points are scored. Since the context does not mention scoring points immediately at the time of overbuilding, we can conclude that the points are likely scored at the end of the current era, as is typical in many games. Therefore, overbuilding a flipped tile does not result in an immediate loss of points, but rather, the points are retained until the end of the era\n\nAnswer:\x1b[32m No, you do not lose out on any points that you would have otherwise scored for the overbuilt tile at the end of the current era. The points are retained and will be scored at the end of the era, as players do not lose previously gained income or VPs when their Industry tiles are overbuilt.\x1b[0m\n\n\n'

## Evaluate compiled prompt

In [77]:
evaluator = Evaluate(devset=test, num_threads=1, display_progress=True, display_table=5)

In [78]:
# launch evaluation
evaluator(answer_generator_compiled, metric=llm_metric)

Average Metric: 10.0 / 40  (25.0): 100%|██████████████████| 40/40 [01:21<00:00,  2.03s/it]

25.0

## Re-evaluate original prompt

Note that it's slightly worse

In [79]:
evaluator(answer_generator, metric=llm_metric)

Average Metric: 9.0 / 40  (22.5): 100%|██████████████████| 40/40 [00:00<00:00, 421.63it/s]

22.5

## Conclusion

In the end, DSPy didn't give me as much of a boost as I wanted. Here are several other things I could try:
- There are several different optimizers (teleprompters) in DSPy. We could try a different optimizer
  - MIPRO is the best one, but it requires several hundred training examples
- max_labeled_demos, max_bootstrapped_demos, and num_candidate_programs are all hyperparameters in BootstrapFewShotWithRandomSearch. We could try different values to see if things improve.
- Most importantly, the computer decides that a prompt is better if the llm_metric function gives better results for the rows in the dev set. We need to verify that we agree with the results from the llm_metric function! If we don't agree with its results then we should change the assessment prompts until we do.